name: Protect Core Files
on: [pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure critical files exist
        run: |
          set -e
          for f in \
            inp-doctor.php \
            includes/class-inpd-plugin.php \
            includes/class-inpd-admin.php \
            includes/class-inpd-rest.php \
            includes/class-inpd-rum.php \
            includes/class-inpd-cron.php \
            composer.json \
            .github/workflows/ci.yml; do
            if [ ! -f "$f" ]; then echo "Missing $f"; exit 1; fi
          done
